### ISSUE TITLE
Panic on dump transformation of table with generated columns

### ISSUE THREAD

**Issue by akademic** [nixys/nxs-data-anonymizer#5]
Trying anonymizer on big mysql dump.

Got this error

```
panic: runtime error: index out of range [34] with length 34

goroutine 2772139 [running]:
github.com/nixys/nxs-data-anonymizer/modules/filters/relfilter.(*Filter).Apply(0xc00019ea80)
	/Users/akademic/projects/lab/nxs-data-anonymizer/modules/filters/relfilter/filter.go:119 +0x2dd
github.com/nixys/nxs-data-anonymizer/modules/anonymizers/mysql.dhCreateTableValuesEnd({0x885c40?, 0xc00019ea80}, {0xc000560000?, 0x1000?, 0xc000585111?}, {0xc000585111?, 0x1?, 0x0?})
	/Users/akademic/projects/lab/nxs-data-anonymizer/modules/anonymizers/mysql/dh.go:61 +0x65
github.com/nixys/nxs-go-fsm.(*FSM).read(0xc000118000, {0xc0001ea000, 0x8000, 0x77f7c5?})
	/Users/akademic/go/pkg/mod/github.com/nixys/nxs-go-fsm@v1.0.0/fsm.go:128 +0x494
github.com/nixys/nxs-go-fsm.(*FSM).Read.func1()
	/Users/akademic/go/pkg/mod/github.com/nixys/nxs-go-fsm@v1.0.0/fsm.go:77 +0x32
created by github.com/nixys/nxs-go-fsm.(*FSM).Read
	/Users/akademic/go/pkg/mod/github.com/nixys/nxs-go-fsm@v1.0.0/fsm.go:76 +0xea
```

Found cause of error.
Mysql table has GENERATED column.
So columns count in create table greater than in INSERT INTO statement.

Sample of "buggy" sql

```
-- Create the table
CREATE TABLE `my_table` (
      `id` INT PRIMARY KEY,
      `first_name` VARCHAR(50),
      `last_name` VARCHAR(50),
      `full_name` VARCHAR(100) GENERATED ALWAYS AS (CONCAT(first_name, ' ', last_name)) STORED
);

-- Insert two records
INSERT INTO `my_table` (id, first_name, last_name) VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
```

**Comment by akademic** [comment]
Found cause of error.
Mysql table has GENERATED column.
So columns count in create table greater than in INSERT INTO statement.

**Comment by akademic** [comment]
Sample of "buggy" sql

```
-- Create the table
CREATE TABLE `my_table` (
      `id` INT PRIMARY KEY,
      `first_name` VARCHAR(50),
      `last_name` VARCHAR(50),
      `full_name` VARCHAR(100) GENERATED ALWAYS AS (CONCAT(first_name, ' ', last_name)) STORED
);

-- Insert two records
INSERT INTO `my_table` (id, first_name, last_name) VALUES (1, 'John', 'Doe'), (2, 'Jane', 'Smith');
```

**Comment by akademic** [comment]
Made PR #6 that fixes bug

**Comment by borisershov** [comment]
I've merged you PR with minor code refactoring. Thanks for your improvements!
